In [37]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from bs4 import BeautifulSoup # library to parse HTML and XML documents

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

print("Libraries imported.")

Libraries imported.

In [38]:
data = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [39]:
soup = BeautifulSoup(data, 'html.parser')

In [50]:
# create three lists to store table data
postalCodeList = []
boroughList = []
neighborhoodList = []

In [71]:
soup.find('table').find_all('tr')

soup.find('table').find_all('tr')

for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')

In [90]:
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')
    if(len(cells) > 0):
        postalCodeList.append(cells[0].text)
        boroughList.append(cells[1].text.rstrip('\n'))
        neighborhoodList.append(cells[2].text.rstrip('\n'))

In [91]:
toronto_df = pd.DataFrame({"PostalCode": postalCodeList,
                           "Borough": boroughList,
                           "Neighborhood": neighborhoodList})
toronto_df.head()

  PostalCode             Borough               Neighborhood
0      M1A\n      Not assigned\n               Not assigned
1      M2A\n      Not assigned\n               Not assigned
2      M3A\n        North York\n                  Parkwoods
3      M4A\n        North York\n           Victoria Village
4      M5A\n  Downtown Toronto\n  Regent Park, Harbourfront

In [92]:
toronto_df_dropna = toronto_df[toronto_df.Borough != "Not assigned\n"].reset_index(drop=True)
toronto_df_dropnaa = toronto_df_dropna[toronto_df_dropna.Borough != "Not assigned"].reset_index(drop=True)

toronto_df_dropnaa.head()

  PostalCode             Borough                                 Neighborhood
0      M3A\n        North York\n                                    Parkwoods
1      M4A\n        North York\n                             Victoria Village
2      M5A\n  Downtown Toronto\n                    Regent Park, Harbourfront
3      M6A\n        North York\n             Lawrence Manor, Lawrence Heights
4      M7A\n  Downtown Toronto\n  Queen's Park, Ontario Provincial Government

In [93]:
toronto_df_grouped = toronto_df_dropnaa.groupby(["PostalCode", "Borough"], as_index=False).agg(lambda x: ", ".join(x))
toronto_df_grouped.head()

  PostalCode        Borough                                       Neighborhood
0        M1B    Scarborough                                     Malvern, Rouge
1      M1B\n    Scarborough                     Malvern, Rouge, Malvern, Rouge
2      M1B\n  Scarborough\n  Malvern, Rouge, Malvern, Rouge, Malvern, Rouge...
3        M1C    Scarborough             Rouge Hill, Port Union, Highland Creek
4      M1C\n    Scarborough  Rouge Hill, Port Union, Highland Creek, Rouge ...

In [95]:
# for Neighborhood="Not assigned", make the value the same as Borough
for index, row in toronto_df_grouped.iterrows():
    if row["Neighborhood"] == "Not assigned":
        row["Neighborhood"] = row["Borough"]
        
toronto_df_grouped.head()

  PostalCode        Borough                                       Neighborhood
0        M1B    Scarborough                                     Malvern, Rouge
1      M1B\n    Scarborough                     Malvern, Rouge, Malvern, Rouge
2      M1B\n  Scarborough\n  Malvern, Rouge, Malvern, Rouge, Malvern, Rouge...
3        M1C    Scarborough             Rouge Hill, Port Union, Highland Creek
4      M1C\n    Scarborough  Rouge Hill, Port Union, Highland Creek, Rouge ...

In [96]:
column_names = ["PostalCode", "Borough", "Neighborhood"]
test_df = pd.DataFrame(columns=column_names)

test_list = ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for postcode in test_list:
    test_df = test_df.append(toronto_df_grouped[toronto_df_grouped["PostalCode"]==postcode], ignore_index=True)
    
test_df

,PostalCode,Borough,Neighborhood
0,M5G,Downtown Toronto,Central Bay Street
1,M2H,North York,Hillcrest Village
2,M4B,East York,"Parkview Hill, Woodbine Gardens"
3,M1J,Scarborough,Scarborough Village
4,M4G,East York,Leaside
5,M4M,East Toronto,Studio District
6,M1R,Scarborough,"Wexford, Maryvale"
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
8,M9L,North York,Humber Summit
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har..."
10,M1B,Scarborough,"Malvern, Rouge"
11,M5A,Downtown Toronto,"Regent Park, Harbourfront"

In [97]:
toronto_df_grouped.shape

(309, 3)